-- 샌드위치냠냠 데이터베이스 초기화 스크립트
-- 데이터베이스 생성 (이미 존재하는 경우 무시)
CREATE DATABASE IF NOT EXISTS sandwich_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sandwich_db;

-- 게시판 및 카테고리 분류 테이블 (MENU_TB)
CREATE TABLE IF NOT EXISTS MENU_TB (
    MENU_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '게시판 및 카테고리 ID',
    MENU_TYPE VARCHAR(10) NOT NULL COMMENT '메뉴 타입 (B: 게시판, C: 카테고리)',
    MENU_NAME VARCHAR(20) NOT NULL COMMENT '명칭',
    MENU_TOP INT COMMENT '상위 메뉴(카테고리일 시, 해당하는 게시판 ID)',
    USED_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용 여부 (Y: 사용, N: 미사용)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    INDEX idx_menu_type (MENU_TYPE),
    INDEX idx_menu_name (MENU_NAME),
    INDEX idx_created_at (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='게시판 및 카테고리 분류 테이블';

-- "이렇게 만들어요" 게시판 테이블 (RECIPE_TB)
CREATE TABLE IF NOT EXISTS RECIPE_TB (
    RECIPE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '레시피 게시글 ID',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    IMAGE_URL VARCHAR(500) COMMENT '이미지 URL',
    AUTHOR_ID INT COMMENT '작성자 ID',
    AUTHOR_NAME VARCHAR(50) COMMENT '작성자 이름',
    CATEGORY INT NOT NULL DEFAULT 3 COMMENT '카테고리 (MENU_TB의 MENU_ID 참조)',
    VIEWS INT DEFAULT 0 COMMENT '조회수',
    DELETED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y: 삭제됨, N: 정상)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    INDEX idx_category (CATEGORY),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_views (VIEWS),
    INDEX idx_recipe_deleted_yn (DELETED_YN),
    CONSTRAINT fk_recipe_category FOREIGN KEY (CATEGORY) REFERENCES MENU_TB(MENU_ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='레시피 게시판 테이블';

-- "정보 공유해요" 게시판 테이블 (TIP_TB)
CREATE TABLE IF NOT EXISTS TIP_TB (
    TIP_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '정보 공유 게시글 ID',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    AUTHOR_ID INT COMMENT '작성자 ID',
    AUTHOR_NAME VARCHAR(50) COMMENT '작성자 이름',
    CATEGORY INT NOT NULL DEFAULT 5 COMMENT '카테고리 (MENU_TB의 MENU_ID 참조)',
    VIEWS INT DEFAULT 0 COMMENT '조회수',
    DELETED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y: 삭제됨, N: 정상)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    INDEX idx_category (CATEGORY),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_views (VIEWS),
    INDEX idx_tip_deleted_yn (DELETED_YN),
    CONSTRAINT fk_tip_category FOREIGN KEY (CATEGORY) REFERENCES MENU_TB(MENU_ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정보 공유 게시판 테이블';

-- 레시피 게시글 본문 테이블 (RECIPE_CONTENT_TB)
CREATE TABLE IF NOT EXISTS RECIPE_CONTENT_TB (
    RECIPE_CONTENT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '레시피 본문 ID',
    RECIPE_ID INT NOT NULL COMMENT '레시피 게시글 ID',
    CONTENT LONGTEXT NOT NULL COMMENT '본문 내용 (HTML 형식, 이미지, 텍스트, 하이퍼링크 등 포함)',
    TAGS TEXT COMMENT '태그 (쉼표로 구분)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    FOREIGN KEY (RECIPE_ID) REFERENCES RECIPE_TB(RECIPE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_recipe_id (RECIPE_ID),
    INDEX idx_created_at (CREATED_AT),
    UNIQUE KEY uk_recipe_id (RECIPE_ID) COMMENT '한 게시글당 하나의 본문만 허용'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='레시피 게시글 본문 테이블';

-- 정보 공유 게시글 본문 테이블 (TIP_CONTENT_TB)
CREATE TABLE IF NOT EXISTS TIP_CONTENT_TB (
    TIP_CONTENT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '정보 공유 본문 ID',
    TIP_ID INT NOT NULL COMMENT '정보 공유 게시글 ID',
    CONTENT LONGTEXT NOT NULL COMMENT '본문 내용 (HTML 형식, 이미지, 텍스트, 하이퍼링크 등 포함)',
    TAGS TEXT COMMENT '태그 (쉼표로 구분)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    FOREIGN KEY (TIP_ID) REFERENCES TIP_TB(TIP_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_tip_id (TIP_ID),
    INDEX idx_created_at (CREATED_AT),
    UNIQUE KEY uk_tip_id (TIP_ID) COMMENT '한 게시글당 하나의 본문만 허용'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정보 공유 게시글 본문 테이블';

-- 댓글 테이블 (COMMENT_TB)
CREATE TABLE IF NOT EXISTS COMMENT_TB (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '댓글 ID',
    POST_TYPE INT NOT NULL COMMENT '게시글 타입 (1: 레시피, 2: 정보공유)',
    POST_ID INT NOT NULL COMMENT '게시글 ID (RECIPE_ID 또는 TIP_ID)',
    CONTENT TEXT NOT NULL COMMENT '댓글 내용',
    AUTHOR_ID INT COMMENT '작성자 ID (추후 인증 기능 추가 시 사용)',
    AUTHOR_NAME VARCHAR(50) NOT NULL COMMENT '작성자 이름',
    DELETED_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 여부 (Y: 삭제됨, N: 정상)',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성시각',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
    INDEX idx_post_type_id (POST_TYPE, POST_ID),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_deleted_yn (DELETED_YN),
    CONSTRAINT fk_comment_post_type FOREIGN KEY (POST_TYPE) REFERENCES MENU_TB(MENU_ID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='댓글 테이블';

-- 레시피 게시글 조인 View (RECIPE_TB + RECIPE_CONTENT_TB + MENU_TB)
CREATE OR REPLACE VIEW V_RECIPE_WITH_CONTENT AS
SELECT 
    r.RECIPE_ID,
    r.TITLE,
    r.IMAGE_URL,
    r.AUTHOR_ID,
    r.AUTHOR_NAME,
    r.CATEGORY,
    m.MENU_NAME AS CATEGORY_NAME,
    r.VIEWS,
    r.CREATED_AT,
    r.UPDATED_AT,
    r.DELETED_YN,
    rc.RECIPE_CONTENT_ID,
    rc.CONTENT,
    rc.TAGS
FROM RECIPE_TB r
LEFT JOIN RECIPE_CONTENT_TB rc ON r.RECIPE_ID = rc.RECIPE_ID
LEFT JOIN MENU_TB m ON r.CATEGORY = m.MENU_ID;

-- 정보 공유 게시글 조인 View (TIP_TB + TIP_CONTENT_TB + MENU_TB)
CREATE OR REPLACE VIEW V_TIP_WITH_CONTENT AS
SELECT 
    t.TIP_ID,
    t.TITLE,
    t.AUTHOR_ID,
    t.AUTHOR_NAME,
    t.CATEGORY,
    m.MENU_NAME AS CATEGORY_NAME,
    t.VIEWS,
    t.CREATED_AT,
    t.UPDATED_AT,
    t.DELETED_YN,
    tc.TIP_CONTENT_ID,
    tc.CONTENT,
    tc.TAGS
FROM TIP_TB t
LEFT JOIN TIP_CONTENT_TB tc ON t.TIP_ID = tc.TIP_ID
LEFT JOIN MENU_TB m ON t.CATEGORY = m.MENU_ID;
