-- 샌드위치냠냠 데이터베이스 초기화 스크립트
-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS sandwich_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sandwich_db;

-- "이렇게 만들어요" 게시판 테이블 (RECIPE_TB)
CREATE TABLE IF NOT EXISTS RECIPE_TB (
    RECIPE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '레시피 게시글 ID',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    IMAGE_URL VARCHAR(500) COMMENT '이미지 URL',
    AUTHOR_ID INT COMMENT '작성자 ID',
    AUTHOR_NAME VARCHAR(50) COMMENT '작성자 이름',
    CATEGORY VARCHAR(20) NOT NULL DEFAULT 'picnic' COMMENT '카테고리 (picnic: 피크닉/홈카페, lunchbox: 데일리 도시락)',
    CONTENT TEXT COMMENT '내용',
    VIEWS INT DEFAULT 0 COMMENT '조회수',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    INDEX idx_category (CATEGORY),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_views (VIEWS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='레시피 게시판 테이블';

-- "정보 공유해요" 게시판 테이블 (TIP_TB)
CREATE TABLE IF NOT EXISTS TIP_TB (
    TIP_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '정보 공유 게시글 ID',
    TITLE VARCHAR(200) NOT NULL COMMENT '제목',
    AUTHOR_ID INT COMMENT '작성자 ID',
    AUTHOR_NAME VARCHAR(50) COMMENT '작성자 이름',
    SUBCATEGORY VARCHAR(20) NOT NULL DEFAULT 'sauce' COMMENT '서브카테고리 (sauce: 소스 배합, tool: 조리 도구, sale: 할인 소식, etc: 기타)',
    CONTENT TEXT COMMENT '내용',
    VIEWS INT DEFAULT 0 COMMENT '조회수',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    INDEX idx_subcategory (SUBCATEGORY),
    INDEX idx_created_at (CREATED_AT),
    INDEX idx_views (VIEWS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='정보 공유 게시판 테이블';
