-- 카테고리 컬럼을 MENU_ID 기반으로 변경하는 마이그레이션 스크립트
USE sandwich_db;

-- 1. 백업 테이블 생성 (안전을 위해)
CREATE TABLE IF NOT EXISTS RECIPE_TB_BACKUP AS SELECT * FROM RECIPE_TB;
CREATE TABLE IF NOT EXISTS TIP_TB_BACKUP AS SELECT * FROM TIP_TB;

-- 2. RECIPE_TB 마이그레이션
-- 2-1. 새로운 컬럼 추가 (임시)
ALTER TABLE RECIPE_TB ADD COLUMN MENU_ID INT COMMENT '카테고리 MENU_ID' AFTER AUTHOR_NAME;

-- 2-2. 기존 CATEGORY 값을 MENU_ID로 매핑
UPDATE RECIPE_TB SET MENU_ID = 3 WHERE CATEGORY = 'picnic';    -- 피크닉/홈카페
UPDATE RECIPE_TB SET MENU_ID = 4 WHERE CATEGORY = 'lunchbox';  -- 데일리 도시락

-- 2-3. 기존 CATEGORY 컬럼 삭제
ALTER TABLE RECIPE_TB DROP COLUMN CATEGORY;

-- 2-4. MENU_ID를 CATEGORY로 이름 변경 (기존 컬럼명 유지)
ALTER TABLE RECIPE_TB CHANGE COLUMN MENU_ID CATEGORY INT NOT NULL DEFAULT 3 COMMENT '카테고리 (MENU_TB의 MENU_ID 참조)';

-- 2-5. 인덱스 재생성
ALTER TABLE RECIPE_TB ADD INDEX idx_category (CATEGORY);

-- 2-6. 외래키 제약조건 추가
ALTER TABLE RECIPE_TB ADD CONSTRAINT fk_recipe_category 
  FOREIGN KEY (CATEGORY) REFERENCES MENU_TB(MENU_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

-- 3. TIP_TB 마이그레이션
-- 3-1. 새로운 컬럼 추가 (임시)
ALTER TABLE TIP_TB ADD COLUMN MENU_ID INT COMMENT '카테고리 MENU_ID' AFTER AUTHOR_NAME;

-- 3-2. 기존 CATEGORY 값을 MENU_ID로 매핑
UPDATE TIP_TB SET MENU_ID = 5 WHERE CATEGORY = 'sauce';  -- 소스 배합
UPDATE TIP_TB SET MENU_ID = 6 WHERE CATEGORY = 'tool';   -- 조리 도구
UPDATE TIP_TB SET MENU_ID = 7 WHERE CATEGORY = 'sale';   -- 할인 소식
UPDATE TIP_TB SET MENU_ID = 8 WHERE CATEGORY = 'etc';    -- 기타

-- 3-3. 기존 CATEGORY 컬럼 삭제
ALTER TABLE TIP_TB DROP COLUMN CATEGORY;

-- 3-4. MENU_ID를 CATEGORY로 이름 변경 (기존 컬럼명 유지)
ALTER TABLE TIP_TB CHANGE COLUMN MENU_ID CATEGORY INT NOT NULL DEFAULT 5 COMMENT '카테고리 (MENU_TB의 MENU_ID 참조)';

-- 3-5. 인덱스 재생성
ALTER TABLE TIP_TB ADD INDEX idx_category (CATEGORY);

-- 3-6. 외래키 제약조건 추가
ALTER TABLE TIP_TB ADD CONSTRAINT fk_tip_category 
  FOREIGN KEY (CATEGORY) REFERENCES MENU_TB(MENU_ID) ON UPDATE CASCADE ON DELETE RESTRICT;

-- 4. View 재생성
DROP VIEW IF EXISTS V_RECIPE_WITH_CONTENT;
CREATE VIEW V_RECIPE_WITH_CONTENT AS
SELECT 
    r.RECIPE_ID,
    r.TITLE,
    r.IMAGE_URL,
    r.AUTHOR_ID,
    r.AUTHOR_NAME,
    r.CATEGORY,
    m.MENU_NAME AS CATEGORY_NAME,
    r.VIEWS,
    r.CREATED_AT,
    r.UPDATED_AT,
    rc.RECIPE_CONTENT_ID,
    rc.CONTENT,
    rc.TAGS
FROM RECIPE_TB r
LEFT JOIN RECIPE_CONTENT_TB rc ON r.RECIPE_ID = rc.RECIPE_ID
LEFT JOIN MENU_TB m ON r.CATEGORY = m.MENU_ID;

DROP VIEW IF EXISTS V_TIP_WITH_CONTENT;
CREATE VIEW V_TIP_WITH_CONTENT AS
SELECT 
    t.TIP_ID,
    t.TITLE,
    t.AUTHOR_ID,
    t.AUTHOR_NAME,
    t.CATEGORY,
    m.MENU_NAME AS CATEGORY_NAME,
    t.VIEWS,
    t.CREATED_AT,
    t.UPDATED_AT,
    tc.TIP_CONTENT_ID,
    tc.CONTENT,
    tc.TAGS
FROM TIP_TB t
LEFT JOIN TIP_CONTENT_TB tc ON t.TIP_ID = tc.TIP_ID
LEFT JOIN MENU_TB m ON t.CATEGORY = m.MENU_ID;

-- 5. 검증 쿼리 (실행 결과 확인용)
SELECT '=== RECIPE_TB 마이그레이션 결과 ===' AS INFO;
SELECT RECIPE_ID, TITLE, CATEGORY, 
       (SELECT MENU_NAME FROM MENU_TB WHERE MENU_ID = RECIPE_TB.CATEGORY) AS CATEGORY_NAME
FROM RECIPE_TB;

SELECT '=== TIP_TB 마이그레이션 결과 ===' AS INFO;
SELECT TIP_ID, TITLE, CATEGORY,
       (SELECT MENU_NAME FROM MENU_TB WHERE MENU_ID = TIP_TB.CATEGORY) AS CATEGORY_NAME
FROM TIP_TB;

SELECT '마이그레이션 완료!' AS STATUS;

